### ISSUE TITLE
Add Dependabot 

### ISSUE THREAD

**Issue by andoriyaprashant** [andoriyaprashant/CanSat#5]

**Comment by JP-sDEV** [comment]
hi @andoriyaprashant, is there a scheduled interval that you want dependabot to run on?

**Comment by andoriyaprashant** [comment]
> hi @andoriyaprashant, is there a scheduled interval that you want dependabot to run on?

Every month

**Comment by JP-sDEV** [comment]
sounds good, could I be assigned this ticket?

**Comment by andoriyaprashant** [comment]
> sounds good, could I be assigned this ticket?

Go ahead
